import type { Item } from './types';

export const MOCK_ITEMS: Item[] = [
  {
    id: 'item-001',
    title: 'Mobile Banking App Upgrade',
    type: 'Project',
    verticalHead: 'Rajesh Kumar',
    businessSpoc: 'Anil Kumar',
    businessSponsor: 'Deepak Mehta',
    requirement: 'Upgrade mobile banking app to support UPI 2.0, biometric login, and personalized dashboard for 5M+ users.',
    outcomeCategory: 'Customer Experience',
    outcomeDescription: 'Improved app rating from 3.2 to 4.5 and 40% increase in daily active users.',
    targetMetric: 'Increase DAU by 40% and app store rating to 4.5',
    goLiveDate: '2026-08-15',
    currentStage: 'Development',
    stageStartDate: '2026-06-01',
    stageExpectedDate: '2026-07-15',
    lastUpdated: '2026-06-14',
    notes: 'Backend API integration 70% complete. UPI 2.0 module under testing.',
    delayed: false,
    committedMonth: '2026-06',
    history: [
      { stage: 'BRD', date: '2026-03-10', user: 'Anita Desai', note: 'BRD signed off by business' },
      { stage: 'FSD', date: '2026-04-05', user: 'Anita Desai', note: 'FSD approved' },
      { stage: 'Commercial', date: '2026-04-25', user: 'Anita Desai', note: 'Vendor selected, PO raised' },
      { stage: 'Development', date: '2026-06-01', user: 'Rajesh Kumar', note: 'Development started' },
    ],
    createdAt: '2026-03-10',
  },
  {
    id: 'item-002',
    title: 'UPI Enhancement v2.0',
    type: 'Change Request',
    verticalHead: 'Priya Sharma',
    businessSpoc: 'Meena Gupta',
    businessSponsor: 'Ramesh Jain',
    requirement: 'Enable UPI AutoPay, recurring mandates, and international UPI transactions per RBI circular.',
    outcomeCategory: 'Revenue',
    outcomeDescription: 'Capture ₹50Cr incremental UPI revenue from recurring payment mandates.',
    targetMetric: 'Increase UPI transaction volume by 25%',
    goLiveDate: '2026-07-15',
    currentStage: 'SIT',
    stageStartDate: '2026-06-05',
    stageExpectedDate: '2026-06-25',
    lastUpdated: '2026-06-14',
    notes: 'SIT cycle 2 in progress. 3 defects pending closure.',
    delayed: false,
    history: [
      { stage: 'BRD', date: '2026-04-01', user: 'Anita Desai', note: 'BRD completed' },
      { stage: 'FSD', date: '2026-04-20', user: 'Anita Desai', note: 'FSD finalized' },
      { stage: 'Commercial', date: '2026-05-05', user: 'Anita Desai', note: 'In-house development approved' },
      { stage: 'Development', date: '2026-05-15', user: 'Priya Sharma', note: 'Dev complete' },
      { stage: 'SIT', date: '2026-06-05', user: 'Priya Sharma', note: 'SIT started' },
    ],
    createdAt: '2026-04-01',
  },
  {
    id: 'item-003',
    title: 'CBS Core Integration',
    type: 'Project',
    verticalHead: 'Amit Patel',
    businessSpoc: 'Rakesh Joshi',
    businessSponsor: 'Sunil Agarwal',
    requirement: 'Integrate new CBS (Core Banking System) with 12 legacy modules including Loans, FD, and Trade Finance.',
    outcomeCategory: 'Efficiency',
    outcomeDescription: 'Reduce batch processing time from 6 hours to 45 minutes.',
    targetMetric: 'Reduce batch processing time by 87%',
    goLiveDate: '2026-09-01',
    currentStage: 'Development',
    stageStartDate: '2026-05-15',
    stageExpectedDate: '2026-06-10',
    lastUpdated: '2026-06-13',
    notes: 'Loan module integration blocked on CBS vendor API documentation. Escalated.',
    delayed: true,
    delaySource: 'Vendor',
    history: [
      { stage: 'BRD', date: '2026-02-10', user: 'Anita Desai', note: 'BRD finalized' },
      { stage: 'FSD', date: '2026-03-01', user: 'Anita Desai', note: 'FSD approved' },
      { stage: 'Commercial', date: '2026-03-20', user: 'Anita Desai', note: 'Contract signed with CBS vendor' },
      { stage: 'Development', date: '2026-05-15', user: 'Amit Patel', note: 'Development started. Vendor delays noted.' },
    ],
    createdAt: '2026-02-10',
  },
  {
    id: 'item-004',
    title: 'KYC Automation System',
    type: 'Project',
    verticalHead: 'Sunita Verma',
    businessSpoc: 'Suman Bose',
    businessSponsor: 'Geeta Krishnan',
    requirement: 'Implement AI-based KYC verification with video KYC, OCR for documents, and real-time CKYC registry check.',
    outcomeCategory: 'Compliance',
    outcomeDescription: 'Reduce KYC TAT from 3 days to 4 hours and achieve 100% regulatory compliance.',
    targetMetric: 'Reduce KYC TAT by 95% to under 4 hours',
    goLiveDate: '2026-09-30',
    currentStage: 'UAT',
    stageStartDate: '2026-06-10',
    stageExpectedDate: '2026-08-01',
    lastUpdated: '2026-06-15',
    notes: 'UAT started. Business team testing video KYC flow.',
    delayed: false,
    history: [
      { stage: 'BRD', date: '2026-01-15', user: 'Anita Desai', note: 'BRD approved' },
      { stage: 'FSD', date: '2026-02-20', user: 'Anita Desai', note: 'FSD finalized with AI vendor' },
      { stage: 'Commercial', date: '2026-03-10', user: 'Anita Desai', note: 'AI vendor contracted' },
      { stage: 'Development', date: '2026-04-01', user: 'Sunita Verma', note: 'Development in progress' },
      { stage: 'SIT', date: '2026-05-20', user: 'Sunita Verma', note: 'SIT completed with 2 minor defects fixed' },
      { stage: 'UAT', date: '2026-06-10', user: 'Sunita Verma', note: 'UAT commenced' },
    ],
    createdAt: '2026-01-15',
  },
  {
    id: 'item-005',
    title: 'Payment Gateway Upgrade',
    type: 'Change Request',
    verticalHead: 'Vikram Singh',
    businessSpoc: 'Priti Sharma',
    businessSponsor: 'Arvind Nair',
    requirement: 'Upgrade payment gateway to support tokenization, 3DS 2.0, and RuPay credit on UPI.',
    outcomeCategory: 'Revenue',
    outcomeDescription: 'Reduce payment failures by 60% and increase merchant onboarding by 30%.',
    targetMetric: 'Reduce payment failure rate from 4.2% to 1.5%',
    goLiveDate: '2026-07-05',
    currentStage: 'CAB Approval',
    stageStartDate: '2026-06-08',
    stageExpectedDate: '2026-06-28',
    lastUpdated: '2026-06-14',
    notes: 'CAB presentation scheduled for June 20. All SIT defects closed.',
    delayed: false,
    committedMonth: '2026-06',
    history: [
      { stage: 'BRD', date: '2026-04-10', user: 'Anita Desai', note: 'BRD signed' },
      { stage: 'FSD', date: '2026-04-28', user: 'Anita Desai', note: 'FSD approved' },
      { stage: 'Commercial', date: '2026-05-08', user: 'Anita Desai', note: 'Vendor PO issued' },
      { stage: 'Development', date: '2026-05-15', user: 'Vikram Singh', note: 'Dev complete' },
      { stage: 'SIT', date: '2026-05-28', user: 'Vikram Singh', note: 'SIT passed' },
      { stage: 'UAT', date: '2026-06-05', user: 'Vikram Singh', note: 'UAT signed off' },
      { stage: 'AppSec', date: '2026-06-06', user: 'Vikram Singh', note: 'AppSec cleared' },
      { stage: 'CAB Approval', date: '2026-06-08', user: 'Vikram Singh', note: 'Submitted to CAB' },
    ],
    createdAt: '2026-04-10',
  },
  {
    id: 'item-006',
    title: 'NACH Mandate Processing',
    type: 'Change Request',
    verticalHead: 'Rajesh Kumar',
    businessSpoc: 'Anil Kumar',
    businessSponsor: 'Deepak Mehta',
    requirement: 'Implement NACH mandate registration, amendment, and cancellation through digital channels per NPCI guidelines.',
    outcomeCategory: 'Cost Saving',
    outcomeDescription: 'Save ₹2Cr annually by eliminating paper-based NACH processing.',
    targetMetric: 'Reduce NACH processing cost by 80%',
    goLiveDate: '2026-09-30',
    currentStage: 'FSD',
    stageStartDate: '2026-06-10',
    stageExpectedDate: '2026-07-30',
    lastUpdated: '2026-06-13',
    notes: 'FSD drafting in progress. NPCI technical specs received.',
    delayed: false,
    history: [
      { stage: 'BRD', date: '2026-05-15', user: 'Anita Desai', note: 'BRD approved' },
      { stage: 'FSD', date: '2026-06-10', user: 'Rajesh Kumar', note: 'FSD drafting started' },
    ],
    createdAt: '2026-05-15',
  },
  {
    id: 'item-007',
    title: 'Retail Loan Origination Portal',
    type: 'Project',
    verticalHead: 'Priya Sharma',
    businessSpoc: 'Meena Gupta',
    businessSponsor: 'Ramesh Jain',
    requirement: 'Build end-to-end digital loan origination portal for retail loans covering personal, home, and auto loans.',
    outcomeCategory: 'Revenue',
    outcomeDescription: 'Increase retail loan disbursement by ₹500Cr per quarter through faster processing.',
    targetMetric: 'Reduce loan processing TAT from 7 days to 24 hours',
    goLiveDate: '2026-11-30',
    currentStage: 'BRD',
    stageStartDate: '2026-06-12',
    stageExpectedDate: '2026-07-20',
    lastUpdated: '2026-06-15',
    notes: 'BRD workshop completed. Document under review.',
    delayed: false,
    history: [
      { stage: 'BRD', date: '2026-06-12', user: 'Anita Desai', note: 'BRD workshop conducted' },
    ],
    createdAt: '2026-06-12',
  },
  {
    id: 'item-008',
    title: 'Trade Finance Digitisation',
    type: 'Project',
    verticalHead: 'Amit Patel',
    businessSpoc: 'Rakesh Joshi',
    businessSponsor: 'Sunil Agarwal',
    requirement: 'Digitize LC issuance, bill discounting, and bank guarantee processes on a blockchain platform.',
    outcomeCategory: 'Efficiency',
    outcomeDescription: 'Reduce trade finance processing time from 5 days to same day.',
    targetMetric: 'Reduce LC processing TAT by 80%',
    goLiveDate: '2026-10-31',
    currentStage: 'Commercial',
    stageStartDate: '2026-05-20',
    stageExpectedDate: '2026-07-05',
    lastUpdated: '2026-06-05',
    notes: 'Vendor evaluation ongoing. Awaiting business sign-off on commercials.',
    delayed: true,
    delaySource: 'Business',
    history: [
      { stage: 'BRD', date: '2026-04-01', user: 'Anita Desai', note: 'BRD approved' },
      { stage: 'FSD', date: '2026-05-01', user: 'Anita Desai', note: 'FSD approved' },
      { stage: 'Commercial', date: '2026-05-20', user: 'Amit Patel', note: 'RFP floated to 3 vendors' },
    ],
    createdAt: '2026-04-01',
  },
  {
    id: 'item-009',
    title: 'Customer 360 Dashboard',
    type: 'Project',
    verticalHead: 'Sunita Verma',
    businessSpoc: 'Suman Bose',
    businessSponsor: 'Geeta Krishnan',
    requirement: 'Build unified customer 360 view for relationship managers integrating all product holdings, transactions, and interactions.',
    outcomeCategory: 'Customer Experience',
    outcomeDescription: 'Improve relationship manager productivity by 35% and increase cross-sell ratio by 20%.',
    targetMetric: 'Increase cross-sell ratio by 20%',
    goLiveDate: '2026-07-31',
    currentStage: 'AppSec',
    stageStartDate: '2026-06-05',
    stageExpectedDate: '2026-06-27',
    lastUpdated: '2026-06-14',
    notes: 'AppSec scanning in progress. 2 medium findings to be addressed.',
    delayed: false,
    history: [
      { stage: 'BRD', date: '2026-02-01', user: 'Anita Desai', note: 'BRD approved' },
      { stage: 'FSD', date: '2026-03-01', user: 'Anita Desai', note: 'FSD approved' },
      { stage: 'Commercial', date: '2026-03-20', user: 'Anita Desai', note: 'In-house build approved' },
      { stage: 'Development', date: '2026-04-01', user: 'Sunita Verma', note: 'Dev started' },
      { stage: 'SIT', date: '2026-05-15', user: 'Sunita Verma', note: 'SIT passed' },
      { stage: 'UAT', date: '2026-06-01', user: 'Sunita Verma', note: 'UAT signed off' },
      { stage: 'AppSec', date: '2026-06-05', user: 'Sunita Verma', note: 'AppSec scan initiated' },
    ],
    createdAt: '2026-02-01',
  },
  {
    id: 'item-010',
    title: 'SWIFT Message Automation',
    type: 'Change Request',
    verticalHead: 'Vikram Singh',
    businessSpoc: 'Priti Sharma',
    businessSponsor: 'Arvind Nair',
    requirement: 'Automate SWIFT MT message processing and reconciliation for correspondent banking operations.',
    outcomeCategory: 'Efficiency',
    outcomeDescription: 'Eliminate 80% manual effort in SWIFT message processing saving 500 man-hours per month.',
    targetMetric: 'Reduce manual processing effort by 80%',
    goLiveDate: '2026-08-31',
    currentStage: 'SIT',
    stageStartDate: '2026-06-08',
    stageExpectedDate: '2026-07-10',
    lastUpdated: '2026-06-15',
    notes: 'SIT underway. MT103 and MT202 flows tested successfully.',
    delayed: false,
    history: [
      { stage: 'BRD', date: '2026-04-15', user: 'Anita Desai', note: 'BRD approved' },
      { stage: 'FSD', date: '2026-05-01', user: 'Anita Desai', note: 'FSD approved' },
      { stage: 'Commercial', date: '2026-05-15', user: 'Anita Desai', note: 'In-house development' },
      { stage: 'Development', date: '2026-05-20', user: 'Vikram Singh', note: 'Dev complete' },
      { stage: 'SIT', date: '2026-06-08', user: 'Vikram Singh', note: 'SIT started' },
    ],
    createdAt: '2026-04-15',
  },
  {
    id: 'item-011',
    title: 'BBPS Bill Payment Integration',
    type: 'Change Request',
    verticalHead: 'Rajesh Kumar',
    businessSpoc: 'Anil Kumar',
    businessSponsor: 'Deepak Mehta',
    requirement: 'Integrate BBPS 2.0 for utility bill payments, insurance premiums, and school fee collection.',
    outcomeCategory: 'Revenue',
    outcomeDescription: 'Generate ₹3Cr revenue from transaction fees on 2M monthly bill payments.',
    targetMetric: 'Achieve 2M monthly BBPS transactions within 3 months of go-live',
    goLiveDate: '2026-06-15',
    currentStage: 'UAT',
    stageStartDate: '2026-05-20',
    stageExpectedDate: '2026-06-05',
    lastUpdated: '2026-06-12',
    notes: 'UAT defects delayed by business testing team resource constraints.',
    delayed: true,
    delaySource: 'IT',
    committedMonth: '2026-06',
    history: [
      { stage: 'BRD', date: '2026-03-01', user: 'Anita Desai', note: 'BRD approved' },
      { stage: 'FSD', date: '2026-03-20', user: 'Anita Desai', note: 'FSD approved' },
      { stage: 'Commercial', date: '2026-04-05', user: 'Anita Desai', note: 'PO issued to NPCI' },
      { stage: 'Development', date: '2026-04-15', user: 'Rajesh Kumar', note: 'Dev complete' },
      { stage: 'SIT', date: '2026-05-10', user: 'Rajesh Kumar', note: 'SIT passed' },
      { stage: 'UAT', date: '2026-05-20', user: 'Rajesh Kumar', note: 'UAT started — delayed' },
    ],
    createdAt: '2026-03-01',
  },
  {
    id: 'item-012',
    title: 'AML Transaction Monitoring',
    type: 'Project',
    verticalHead: 'Priya Sharma',
    businessSpoc: 'Meena Gupta',
    businessSponsor: 'Ramesh Jain',
    requirement: 'Implement AI-powered AML transaction monitoring system to replace legacy rule-based engine.',
    outcomeCategory: 'Risk Reduction',
    outcomeDescription: 'Reduce false positive AML alerts by 70% and improve suspicious transaction detection by 40%.',
    targetMetric: 'Reduce AML false positives from 92% to 30%',
    goLiveDate: '2026-11-30',
    currentStage: 'Development',
    stageStartDate: '2026-06-01',
    stageExpectedDate: '2026-08-15',
    lastUpdated: '2026-06-14',
    notes: 'ML model training underway on 3 years of transaction data.',
    delayed: false,
    history: [
      { stage: 'BRD', date: '2026-03-01', user: 'Anita Desai', note: 'BRD approved' },
      { stage: 'FSD', date: '2026-04-01', user: 'Anita Desai', note: 'FSD approved' },
      { stage: 'Commercial', date: '2026-05-01', user: 'Anita Desai', note: 'AI vendor contracted' },
      { stage: 'Development', date: '2026-06-01', user: 'Priya Sharma', note: 'Model training started' },
    ],
    createdAt: '2026-03-01',
  },
  {
    id: 'item-013',
    title: 'Digital Onboarding Revamp',
    type: 'Project',
    verticalHead: 'Amit Patel',
    businessSpoc: 'Rakesh Joshi',
    businessSponsor: 'Sunil Agarwal',
    requirement: 'Revamp end-to-end digital account opening journey with e-KYC, e-sign, and instant account activation.',
    outcomeCategory: 'Customer Experience',
    outcomeDescription: 'Reduce account opening TAT from 3 days to 15 minutes.',
    targetMetric: 'Reduce onboarding TAT to under 15 minutes',
    goLiveDate: '2026-06-22',
    currentStage: 'Go Live',
    stageStartDate: '2026-06-12',
    stageExpectedDate: '2026-06-22',
    lastUpdated: '2026-06-15',
    notes: 'Production deployment planned for June 22. DR drill completed.',
    delayed: false,
    committedMonth: '2026-06',
    history: [
      { stage: 'BRD', date: '2026-01-10', user: 'Anita Desai', note: 'BRD approved' },
      { stage: 'FSD', date: '2026-02-01', user: 'Anita Desai', note: 'FSD approved' },
      { stage: 'Commercial', date: '2026-02-20', user: 'Anita Desai', note: 'In-house development' },
      { stage: 'Development', date: '2026-03-01', user: 'Amit Patel', note: 'Dev complete' },
      { stage: 'SIT', date: '2026-04-01', user: 'Amit Patel', note: 'SIT passed' },
      { stage: 'UAT', date: '2026-05-01', user: 'Amit Patel', note: 'UAT signed off' },
      { stage: 'AppSec', date: '2026-05-20', user: 'Amit Patel', note: 'AppSec cleared' },
      { stage: 'CAB Approval', date: '2026-06-01', user: 'Amit Patel', note: 'CAB approved' },
      { stage: 'Go Live', date: '2026-06-12', user: 'Amit Patel', note: 'Deployment prep started' },
    ],
    createdAt: '2026-01-10',
  },
  {
    id: 'item-014',
    title: 'Debit Card Management System',
    type: 'Change Request',
    verticalHead: 'Sunita Verma',
    businessSpoc: 'Suman Bose',
    businessSponsor: 'Geeta Krishnan',
    requirement: 'Implement self-service debit card management — hotlisting, limit changes, PIN generation via app.',
    outcomeCategory: 'Customer Experience',
    outcomeDescription: 'Reduce call center volume by 30% for card-related queries.',
    targetMetric: 'Reduce card-related call center calls by 30%',
    goLiveDate: '2026-06-10',
    currentStage: 'Business Validation',
    stageStartDate: '2026-06-14',
    stageExpectedDate: '2026-06-20',
    lastUpdated: '2026-06-15',
    notes: 'Awaiting business validation from SPOC team.',
    delayed: false,
    committedMonth: '2026-06',
    history: [
      { stage: 'BRD', date: '2026-02-15', user: 'Anita Desai', note: 'BRD approved' },
      { stage: 'FSD', date: '2026-03-05', user: 'Anita Desai', note: 'FSD approved' },
      { stage: 'Commercial', date: '2026-03-20', user: 'Anita Desai', note: 'In-house development' },
      { stage: 'Development', date: '2026-04-01', user: 'Sunita Verma', note: 'Dev complete' },
      { stage: 'SIT', date: '2026-04-25', user: 'Sunita Verma', note: 'SIT passed' },
      { stage: 'UAT', date: '2026-05-15', user: 'Sunita Verma', note: 'UAT signed off' },
      { stage: 'AppSec', date: '2026-05-28', user: 'Sunita Verma', note: 'AppSec cleared' },
      { stage: 'CAB Approval', date: '2026-06-01', user: 'Sunita Verma', note: 'CAB approved' },
      { stage: 'Go Live', date: '2026-06-10', user: 'Sunita Verma', note: 'Successfully deployed to production' },
      { stage: 'Business Validation', date: '2026-06-14', user: 'Sunita Verma', note: 'Moved to business validation stage' },
    ],
    createdAt: '2026-02-15',
  },
  {
    id: 'item-015',
    title: 'Forex Rate Feed Integration',
    type: 'Change Request',
    verticalHead: 'Vikram Singh',
    businessSpoc: 'Priti Sharma',
    businessSponsor: 'Arvind Nair',
    requirement: 'Integrate real-time forex rate feed from Bloomberg for treasury and retail FX transactions.',
    outcomeCategory: 'Risk Reduction',
    outcomeDescription: 'Reduce FX exposure risk by real-time hedging with live market rates.',
    targetMetric: 'Eliminate FX rate lag to under 5 seconds',
    goLiveDate: '2026-09-30',
    currentStage: 'FSD',
    stageStartDate: '2026-06-10',
    stageExpectedDate: '2026-07-25',
    lastUpdated: '2026-06-13',
    notes: 'FSD in progress. Bloomberg API specification received.',
    delayed: false,
    history: [
      { stage: 'BRD', date: '2026-05-10', user: 'Anita Desai', note: 'BRD approved' },
      { stage: 'FSD', date: '2026-06-10', user: 'Vikram Singh', note: 'FSD started' },
    ],
    createdAt: '2026-05-10',
  },
  {
    id: 'item-016',
    title: 'Mobile POS Merchant App',
    type: 'Project',
    verticalHead: 'Rajesh Kumar',
    businessSpoc: 'Anil Kumar',
    businessSponsor: 'Deepak Mehta',
    requirement: 'Develop mobile POS application for merchant acceptance of card, UPI, and QR payments.',
    outcomeCategory: 'Revenue',
    outcomeDescription: 'Onboard 10,000 new merchants generating ₹8Cr annual fee revenue.',
    targetMetric: 'Onboard 10,000 merchants within 6 months',
    goLiveDate: '2026-05-31',
    currentStage: 'Closed',
    stageStartDate: '2026-05-25',
    stageExpectedDate: '2026-05-31',
    lastUpdated: '2026-06-01',
    notes: 'Successfully delivered. 2,500 merchants onboarded in first 2 weeks.',
    delayed: false,
    committedMonth: '2026-05',
    validation: {
      outcomeAchieved: 'Yes',
      actualResult: 'App launched on time. 2,500 merchants onboarded in first 2 weeks. Payment acceptance working smoothly.',
      actualMetric: '2,500 merchants onboarded (target: 10,000 in 6 months — on track)',
    },
    history: [
      { stage: 'BRD', date: '2025-11-01', user: 'Anita Desai', note: 'BRD approved' },
      { stage: 'FSD', date: '2025-12-01', user: 'Anita Desai', note: 'FSD approved' },
      { stage: 'Commercial', date: '2025-12-20', user: 'Anita Desai', note: 'Vendor contracted' },
      { stage: 'Development', date: '2026-02-01', user: 'Rajesh Kumar', note: 'Dev started' },
      { stage: 'SIT', date: '2026-03-15', user: 'Rajesh Kumar', note: 'SIT passed' },
      { stage: 'UAT', date: '2026-04-10', user: 'Rajesh Kumar', note: 'UAT signed off' },
      { stage: 'AppSec', date: '2026-04-25', user: 'Rajesh Kumar', note: 'AppSec cleared' },
      { stage: 'CAB Approval', date: '2026-05-01', user: 'Rajesh Kumar', note: 'CAB approved' },
      { stage: 'Go Live', date: '2026-05-20', user: 'Rajesh Kumar', note: 'Deployed to production' },
      { stage: 'Business Validation', date: '2026-05-25', user: 'Anil Kumar', note: 'Business validation completed' },
      { stage: 'Closed', date: '2026-06-01', user: 'Anita Desai', note: 'Item closed successfully' },
    ],
    createdAt: '2025-11-01',
  },
  {
    id: 'item-017',
    title: 'Loan Account Statement API',
    type: 'Change Request',
    verticalHead: 'Priya Sharma',
    businessSpoc: 'Meena Gupta',
    businessSponsor: 'Ramesh Jain',
    requirement: 'Expose loan account statement via API for AA (Account Aggregator) framework integration.',
    outcomeCategory: 'Compliance',
    outcomeDescription: 'Achieve RBI AA framework compliance and enable customer data portability.',
    targetMetric: 'AA framework compliance by RBI deadline',
    goLiveDate: '2026-08-31',
    currentStage: 'Commercial',
    stageStartDate: '2026-05-25',
    stageExpectedDate: '2026-06-08',
    lastUpdated: '2026-06-13',
    notes: 'Commercial negotiations delayed due to AA aggregator pricing dispute.',
    delayed: true,
    delaySource: 'External',
    history: [
      { stage: 'BRD', date: '2026-04-20', user: 'Anita Desai', note: 'BRD approved' },
      { stage: 'FSD', date: '2026-05-10', user: 'Anita Desai', note: 'FSD approved' },
      { stage: 'Commercial', date: '2026-05-25', user: 'Priya Sharma', note: 'Vendor negotiations started' },
    ],
    createdAt: '2026-04-20',
  },
  {
    id: 'item-018',
    title: 'Treasury Management System Upgrade',
    type: 'Project',
    verticalHead: 'Amit Patel',
    businessSpoc: 'Rakesh Joshi',
    businessSponsor: 'Sunil Agarwal',
    requirement: 'Upgrade TMS to support ALM, liquidity management, and real-time position monitoring.',
    outcomeCategory: 'Risk Reduction',
    outcomeDescription: 'Reduce treasury operational risk and achieve Basel III liquidity reporting compliance.',
    targetMetric: 'Achieve 100% Basel III LCR compliance by Dec 2026',
    goLiveDate: '2026-10-31',
    currentStage: 'SIT',
    stageStartDate: '2026-06-08',
    stageExpectedDate: '2026-07-05',
    lastUpdated: '2026-06-15',
    notes: 'SIT in progress. ALM module testing underway.',
    delayed: false,
    history: [
      { stage: 'BRD', date: '2026-02-15', user: 'Anita Desai', note: 'BRD approved' },
      { stage: 'FSD', date: '2026-03-15', user: 'Anita Desai', note: 'FSD approved' },
      { stage: 'Commercial', date: '2026-04-01', user: 'Anita Desai', note: 'Vendor contracted' },
      { stage: 'Development', date: '2026-05-01', user: 'Amit Patel', note: 'Dev started' },
      { stage: 'SIT', date: '2026-06-08', user: 'Amit Patel', note: 'SIT commenced' },
    ],
    createdAt: '2026-02-15',
  },
  {
    id: 'item-019',
    title: 'Customer Grievance Portal',
    type: 'Project',
    verticalHead: 'Sunita Verma',
    businessSpoc: 'Suman Bose',
    businessSponsor: 'Geeta Krishnan',
    requirement: 'Build integrated customer grievance portal with auto-routing, SLA tracking, and RBI reporting.',
    outcomeCategory: 'Compliance',
    outcomeDescription: 'Reduce grievance TAT from 30 days to 7 days and achieve 100% RBI TAT compliance.',
    targetMetric: 'Reduce grievance resolution TAT by 77%',
    goLiveDate: '2026-10-31',
    currentStage: 'BRD',
    stageStartDate: '2026-06-08',
    stageExpectedDate: '2026-06-26',
    lastUpdated: '2026-06-14',
    notes: 'BRD in progress. Legal and compliance inputs pending.',
    delayed: false,
    history: [
      { stage: 'BRD', date: '2026-06-08', user: 'Anita Desai', note: 'BRD initiated' },
    ],
    createdAt: '2026-06-08',
  },
  {
    id: 'item-020',
    title: 'IMPS Real-time Settlement Upgrade',
    type: 'Change Request',
    verticalHead: 'Vikram Singh',
    businessSpoc: 'Priti Sharma',
    businessSponsor: 'Arvind Nair',
    requirement: 'Upgrade IMPS infrastructure to handle 10x volume growth and achieve 99.99% uptime per NPCI SLA.',
    outcomeCategory: 'Efficiency',
    outcomeDescription: 'Support ₹50,000Cr daily IMPS settlement with zero downtime.',
    targetMetric: 'Achieve 99.99% IMPS uptime and 10x throughput',
    goLiveDate: '2026-07-31',
    currentStage: 'CAB Approval',
    stageStartDate: '2026-05-30',
    stageExpectedDate: '2026-07-01',
    lastUpdated: '2026-06-04',
    notes: 'No update received from team. Escalation required.',
    delayed: false,
    history: [
      { stage: 'BRD', date: '2026-03-01', user: 'Anita Desai', note: 'BRD approved' },
      { stage: 'FSD', date: '2026-04-01', user: 'Anita Desai', note: 'FSD approved' },
      { stage: 'Commercial', date: '2026-04-20', user: 'Anita Desai', note: 'Infrastructure vendor selected' },
      { stage: 'Development', date: '2026-05-01', user: 'Vikram Singh', note: 'Dev complete' },
      { stage: 'SIT', date: '2026-05-15', user: 'Vikram Singh', note: 'SIT passed' },
      { stage: 'UAT', date: '2026-05-25', user: 'Vikram Singh', note: 'UAT cleared' },
      { stage: 'AppSec', date: '2026-05-28', user: 'Vikram Singh', note: 'AppSec cleared' },
      { stage: 'CAB Approval', date: '2026-05-30', user: 'Vikram Singh', note: 'Submitted to CAB — no update since' },
    ],
    createdAt: '2026-03-01',
  },
];
